export const VIDEO_SET_WE_CALL_THEM_POOR = 'We_Call_Them_Poor'
export const VIDEO_SET_2026_BTC_CRASH = '2026_BTC_Crash'
export const VIDEO_SET_BATTLESHIP = 'Battleship'
export const VIDEO_SET_FORD_VS_FERRARI = 'Ford_vs_Ferrari'
export const VIDEO_SET_MATRIX = 'Matrix'
export const VIDEO_SET_INTERSTELLAR_SAYLOR = 'Interstellar_Saylor'
export const VIDEO_SET_NO_SECOND_BEST = 'No_Second_Best'
export const VIDEO_SET_SAYLOR_SIGH = 'Saylor_Sigh'
export const VIDEO_SET_SHOW_YOU_THE_DOOR = 'Show_you_the_Door'
export const VIDEO_SET_GET_ON_THE_ARK = 'Get_on_the_Ark'
export const VIDEO_SET_FIAT_SYSTEM = 'Fiat_System'
export const VIDEO_SET_EXIT_FIAT_ENTER_BITCOIN = 'Exit_Fiat_Enter_Bitcoin'
export const VIDEO_SET_BITCOIN_RAP_BATTLE = 'Bitcoin_Rap_Battle'
export const VIDEO_SET_ONE_CHAIR = 'One_Chair'
export const VIDEO_SET_MONEY_MONEY = 'Money_Money'
export const VIDEO_SET_WELCOME_BLOCKCHAIN = 'Welcome_Blockchain'
export const VIDEO_SET_BLOCKCHAIN_BLOOD = 'Blockchain_Blood'

export const VIDEO_SET_TO_VIDEO_ID: Record<string, string> = {
  [VIDEO_SET_WE_CALL_THEM_POOR]: 'B5if2hthPCs',
  [VIDEO_SET_2026_BTC_CRASH]: 'NTpFZLDoxI0',
  [VIDEO_SET_BATTLESHIP]: 'z-YKKKLwtiw',
  [VIDEO_SET_FORD_VS_FERRARI]: 'FrAqyC3AuhA',
  [VIDEO_SET_MATRIX]: 'y1GKMmAcd2I',
  [VIDEO_SET_INTERSTELLAR_SAYLOR]: 'QhpyJSHx8LI',
  [VIDEO_SET_NO_SECOND_BEST]: 'wIhTGB3wqV0',
  [VIDEO_SET_SAYLOR_SIGH]: '2VqIBmFxMKY',
  [VIDEO_SET_SHOW_YOU_THE_DOOR]: 'xc3VG9JZM6I',
  [VIDEO_SET_GET_ON_THE_ARK]: 'uYO5L88h26Y',
  [VIDEO_SET_FIAT_SYSTEM]: 'rztpVMqkdug',
  [VIDEO_SET_EXIT_FIAT_ENTER_BITCOIN]: 'nOh-7SzI6gM',
  [VIDEO_SET_BITCOIN_RAP_BATTLE]: 'JaMJi1_1tkA',
  [VIDEO_SET_ONE_CHAIR]: 'qjjNgW4bZm8',
  [VIDEO_SET_MONEY_MONEY]: '82bSw5uAkBQ',
  [VIDEO_SET_WELCOME_BLOCKCHAIN]: 'YbzNJr26H-4',
  [VIDEO_SET_BLOCKCHAIN_BLOOD]: 'SBhOcuNKeIE',
}

/** Mirrors Android active list (`VIDEO_OVERLAY_SET_IDS`). */
export const VIDEO_OVERLAY_SET_IDS = [
  VIDEO_SET_WE_CALL_THEM_POOR,
  VIDEO_SET_2026_BTC_CRASH,
  VIDEO_SET_BATTLESHIP,
  VIDEO_SET_FORD_VS_FERRARI,
  VIDEO_SET_MATRIX,
  VIDEO_SET_INTERSTELLAR_SAYLOR,
  VIDEO_SET_NO_SECOND_BEST,
  VIDEO_SET_SAYLOR_SIGH,
  VIDEO_SET_SHOW_YOU_THE_DOOR,
  VIDEO_SET_GET_ON_THE_ARK,
  VIDEO_SET_FIAT_SYSTEM,
  VIDEO_SET_EXIT_FIAT_ENTER_BITCOIN,
  VIDEO_SET_BITCOIN_RAP_BATTLE,
  VIDEO_SET_ONE_CHAIR,
  VIDEO_SET_MONEY_MONEY,
  VIDEO_SET_WELCOME_BLOCKCHAIN,
  VIDEO_SET_BLOCKCHAIN_BLOOD,
] as const

